FROM karelbemelmans/d7-docker-base
MAINTAINER Karel Bemelmans <mail@karelbemelmans.com>

# Copy our local settings.php file into the container.
# This file is generated by the AWS CF LaunchConfiguration during the stack
# creation. An example file is provided here.
COPY settings.php sites/default/settings.php

# Install extra modules using the d7download.sh script from the base image.
#
# Modules

# Themes

# Libraries

# Apply patches if needed

#

# Done.
