version: '2'
services:
  drupal:
    build: .
    ports:
      - "80:80"
    links:
      - db
      - redis
    environment:
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASS: drupal
      DRUPAL_DB_HOST: db
      DRUPAL_DB_PREFIX: drupal_
      DRUPAL_REDIS_HOST: redis
      DRUPAL_REDIS_PORT: 6379
    volumes:
      - ./sites/default/files:/var/www/html/sites/default/files
      - ./private:/data/private

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  redis:
    image: redis
